{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
  - name: {{ .Values.serviceAccount.secretName }}
metadata:
  name: {{ include "hello-world.serviceAccountName" . }}
  labels:
    {{- include "hello-world.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
