name: Build and Deploy to DOKS

on:
  push:
    branches:
    - master

# Environment variables available to all jobs and steps in this workflow
env:
  GITHUB_SHA: ${{ github.sha }}
  DOKS_CLUSTER: app-exploration
  REGISTRY_HOSTNAME: registry.digitalocean.com
  REGISTRY_NAME: ntate
  IMAGE: hello-world
  HELM_REPO: helm-repository
  DEPLOYMENT_NAME: hello-world-deployment

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
  
    - name: Save DigitalOcean kubeconfig
      run: doctl kubernetes cluster kubeconfig show $DOKS_CLUSTER > ./kubeconfig.yml
      
    - name: Login to DOCR registry
      run: doctl registry login

    - name: Ensure secrets on cluster 
      run: doctl registry kubernetes-manifest > ./docr-secret.yml

    - name: Deploy to cluster
      uses: stefanprodan/kube-tools@v1
      with:
        kubectl: 1.18.2
        command: |
          export KUBECONFIG=./kubeconfig.yml
          kubectl apply -f ./docr-secret.yml
          kubectl patch serviceaccount default -p '{"imagePullSecrets": [{"name": "registry-ntate"}]}'

      
    - name: Build
      run: |        
        docker build -t "$REGISTRY_HOSTNAME"/"$REGISTRY_NAME"/"$IMAGE":"$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" .

    - name: Publish
      run: |
        docker push $REGISTRY_HOSTNAME/$REGISTRY_NAME/$IMAGE:$GITHUB_SHA
        
    - name: Save and publish potential chart changes
      uses: stefanprodan/kube-tools@v1
      with:
        helmv3: 3.2.1
        command: |
           export HELM_EXPERIMENTAL_OCI=1
           helmv3 registry login registry.digitalocean.com --username ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} --password ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
           helmv3 chart save ./chart $REGISTRY_HOSTNAME/$REGISTRY_NAME/$HELM_REPO/$IMAGE:$GITHUB_SHA
           helmv3 chart push $REGISTRY_HOSTNAME/$REGISTRY_NAME/$HELM_REPO/$IMAGE:$GITHUB_SHA
    
    - name: Deploy to cluster
      uses: stefanprodan/kube-tools@v1
      with:
        helmv3: 3.2.1
        command: |
          export KUBECONFIG=./kubeconfig.yml
          export HELM_EXPERIMENTAL_OCI=1
          helmv3 chart export $REGISTRY_HOSTNAME/$REGISTRY_NAME/$HELM_REPO/$IMAGE:$GITHUB_SHA -d install
          if ! helmv3 status $DEPLOYMENT_NAME > /dev/null; then
            helmv3 install $DEPLOYMENT_NAME ./install/$IMAGE --set image.tag=$GITHUB_SHA 
          else
            helmv3 upgrade $DEPLOYMENT_NAME ./install/$IMAGE --set image.tag=$GITHUB_SHA
          fi

